version: '3.7'

services:
  riskengine:   # Readmission Risk LACE Service
    image: containers.intersystems.com/intersystems/iris:2021.1.0.215.0
    hostname: riskengine
    init: true
    command:
      --key /home/irisowner/license/iris.key
    ports:
    - "9095:1972" # 1972 is the superserver default port
    - "9094:52773" # 52773 is the webserver/management portal port
    volumes:
    - ./license:/home/irisowner/license
    - ./UserCPF:/home/irisowner/cpf
    environment:
    - ISC_CPF_MERGE_FILE=/home/irisowner/cpf/merge.cpf
    - TZ=JST-9

  zeppelin:
    build:
      context: ./zeppelin/build
    volumes: 
        - ./zeppelin/shared:/shared
    environment:
    - ZEPPELIN_LOG_DIR=/shared/logs
    - ZEPPELIN_NOTEBOOK_DIR=/shared/notebook
    - ZEPPELIN_CONF_DIR=/shared/conf
    - TZ=JST-9
    ports:
    - "10000:9090"     # Zeppelin        

  sparkmaster:
    build:
      context: ./spark/build
    hostname: sparkmaster # Must be always sparkmaster
    init: true
    user: root
    depends_on:
    - zeppelin
    environment:
      SPARK_PUBLIC_DNS: irishost
      IRIS_MASTER_HOST: riskengine
      IRIS_MASTER_PORT: 1972
      IRIS_MASTER_USERNAME: SuperUser
      IRIS_MASTER_PASSWORD: SYS
      IRIS_MASTER_NAMESPACE: USER
      TZ: JST-9
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080   # Spark Master Portal
    volumes:
    - type: bind
      source: ./spark/shared/
      target: /shared

  worker1:
    depends_on:
      - sparkmaster
    build:
      context: ./spark/build
    hostname: worker1
    init: true
    user: root
    environment:
      IRIS_MASTER_HOST: riskengine
      IRIS_MASTER_PORT: 1972
      IRIS_MASTER_USERNAME: SuperUser
      IRIS_MASTER_PASSWORD: SYS
      IRIS_MASTER_NAMESPACE: USER
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://sparkmaster:7077      
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g   # You can give more memory to your work if you are getting errors when using Spark
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: irishost
      TZ: JST-9
    ports:
      - 8081:8081   # Spark Worker Portal # this prevent "docker-compose up -d --scale worker1=2" from succeeding...
    volumes:
    - type: bind
      source: ./spark/shared/
      target: /shared

  worker2:
    depends_on:
      - sparkmaster
    build:
      context: ./spark/build
    hostname: worker2
    init: true
    user: root
    environment:
      IRIS_MASTER_HOST: riskengine
      IRIS_MASTER_PORT: 1972
      IRIS_MASTER_USERNAME: SuperUser
      IRIS_MASTER_PASSWORD: SYS
      IRIS_MASTER_NAMESPACE: USER
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://sparkmaster:7077      
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g   # You can give more memory to your work if you are getting errors when using Spark
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
      SPARK_PUBLIC_DNS: irishost
      TZ: JST-9
    ports:
    - 8082:8082 #Spark Worker Portal
    volumes:
    - type: bind
      source: ./spark/shared/
      target: /shared
